import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { AuthProvider } from "@/hooks/useAuth";
import { ThemeProvider } from "next-themes";
import { Slide, ToastContainer } from "react-toastify";
import { AppProgressBar as ProgressBar } from "next-nprogress-bar";
import Footer from "@/components/Footer";
import "react-toastify/dist/ReactToastify.css";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class">
          <AuthProvider>
            <ToastContainer
              position="bottom-right"
              autoClose={2000}
              theme="colored"
              transition={Slide}
              hideProgressBar={false}
              closeOnClick
              newestOnTop
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover={false}
            />
            <NextTopLoader />
            <div className="bg-white text-black dark:bg-neutral-950  dark:text-gray-100 min-h-screen">
              <Navbar />
              {children}
              <Footer />
            </div>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
